### ISSUE TITLE
Nothing compiled

### ISSUE THREAD

**Issue by kostyamat** [LGTMCU/Larduino_HSP#3]
Hi,
I can not compile anything. Although fully complied with all the conditions specified in the file readme. The installation path is correct. All is correct, but I have error
"C:\\Users\\Konstyantyn\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_LARDU_328E -DARDUINO_ARCH_AVR "-ID:\\Konstyantyn\\Documents\\Arduino\\hardware\\LGT\\avr\\cores\\lgt8f" "-ID:\\Konstyantyn\\Documents\\Arduino\\hardware\\LGT\\avr\\variants\\lgt8fx8p" "D:\\Konstyantyn\\Documents\\Arduino\\hardware\\LGT\\avr\\cores\\lgt8f\\wiring_analog.c" -o "C:\\Users\\KONSTY~1\\AppData\\Local\\Temp\\arduino_build_105324\\core\\wiring_analog.c.o"
"C:\\Users\\Konstyantyn\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_LARDU_328E -DARDUINO_ARCH_AVR "-ID:\\Konstyantyn\\Documents\\Arduino\\hardware\\LGT\\avr\\cores\\lgt8f" "-ID:\\Konstyantyn\\Documents\\Arduino\\hardware\\LGT\\avr\\variants\\lgt8fx8p" "D:\\Konstyantyn\\Documents\\Arduino\\hardware\\LGT\\avr\\cores\\lgt8f\\hooks.c" -o "C:\\Users\\KONSTY~1\\AppData\\Local\\Temp\\arduino_build_105324\\core\\hooks.c.o"
"C:\\Users\\Konstyantyn\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_LARDU_328E -DARDUINO_ARCH_AVR "-ID:\\Konstyantyn\\Documents\\Arduino\\hardware\\LGT\\avr\\cores\\lgt8f" "-ID:\\Konstyantyn\\Documents\\Arduino\\hardware\\LGT\\avr\\variants\\lgt8fx8p" "D:\\Konstyantyn\\Documents\\Arduino\\hardware\\LGT\\avr\\cores\\lgt8f\\wiring_pulse.c" -o "C:\\Users\\KONSTY~1\\AppData\\Local\\Temp\\arduino_build_105324\\core\\wiring_pulse.c.o"
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

exit status 1
Ошибка компиляции для платы LGT8F328P-LQFP32 MiniEVB.

In this case, I just tried to compile one of the examples for your board.
Will there be any help from your side?

**Comment by curliph** [comment]
Recommended to try with Arduino IDE 1.8.x or more recently version.
I usually test the package with Arduino ide 1.8.5

B.R

**Comment by kostyamat** [comment]
I am using last 1.8.9 version of Arduino ide.

**Comment by curliph** [comment]
Hi  Kostyamat,

I have just test hsp with arduino ide 1.8.9 (portable version),  seems there is no problem.
I notices your error message report ccl.exe running with “-fno-fat-lto-objects" which is not supported.
but I can not find "-fno-fat-lto-objects" parameter in my case.  
So please double check your settings or try a portable version of arduino ide.
 
B.R

**Comment by kostyamat** [comment]
Good. I installed IDE version 1.8.5 and managed to compile several sketches. It looks like a problem in the IDE of newer versions.

**Comment by mcer12** [comment]
This is unacceptable as a solution, this is not Arduino IDE bug, it should work in new IDE version. Please reopen this issue for fixing.

**Comment by kostyamat** [comment]
I have had problems not only with this MCU, but with several others in recent versions of the Arduino IDE. Therefore, the problem seems to be on the side of the developers of Arduino IDE. But version 18.5 proved to be stable in all cases. I see no reason to reopen this issue.

**Comment by mcer12** [comment]
The MCUs you work with are probably incompatible with current version and need their board definitions updated. Sticking with outdated version of IDE works but its not a solution.
